TRUNCATE tbl_budget_request;
TRUNCATE tbl_grants;
TRUNCATE tbl_line_items;
TRUNCATE tbl_manage;
TRUNCATE tbl_projects;
TRUNCATE tbl_sponsors;
TRUNCATE tbl_trans;
TRUNCATE tbl_documents;
TRUNCATE tbl_announcements;
DELETE from tbl_users where id !=1;